spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:~/test
    initialization-mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true



